mpu6050driver_node:
  ros__parameters:
    calibrate: true
    # Gyroscope range: 0 -> +-250°/s, 1 -> +-500°/s, 2 -> +-1000°/s, 3 -> +-2000°/s
    gyro_range: 3
    # Acceleration range: 0 -> +-2g, 1 -> +-4g, 2 -> +-8g, 3 -> +-16g
    accel_range: 3
    # Digital low pass filter bandwidth [0-6]: 0 -> 260Hz, 1 -> 184Hz, 2 -> 94Hz, 3 -> 44Hz, 4 -> 21Hz, 5 -> 10Hz, 6 -> 5Hz
    dlpf_bandwidth: 2
    #If "calibrate" is true, these values will be overriden by the calibration procedure
    gyro_x_offset: -1.46326 # [deg/s]
    gyro_y_offset: -0.608614 # [deg/s]
    gyro_z_offset: -2.84698 # [deg/s]
    accel_x_offset: 0.29498 # [m/s²]
    accel_y_offset: 0.181014 # [m/s²]
    accel_z_offset: -1.60613 # [m/s²]
    # gyro_x_offset: 0.0 # [deg/s]
    # gyro_y_offset: 0.0 # [deg/s]
    # gyro_z_offset: 0.0 # [deg/s]
    # accel_x_offset: 0.0 # [m/s²]
    # accel_y_offset: 0.0 # [m/s²]
    # accel_z_offset: 0.0 # [m/s²]
    frequency: 100 # [Hz]
